#ifndef ATG_PALACE_ENGINE_GRAPHICS_SUPPORT_HPP
#define ATG_PALACE_ENGINE_GRAPHICS_SUPPORT_HPP

#include "graphics_api_object.hpp"

#if defined(PALACE_CMAKE_VULKAN_DEPENDENCY_FOUND)
#define PALACE_SUPPORTS_VULKAN 1
#endif

#endif /* ATG_PALACE_ENGINE_GRAPHICS_SUPPORT_HPP */
