#ifndef ATG_PALACE_ENGINE_LOG_LEVEL_HPP
#define ATG_PALACE_ENGINE_LOG_LEVEL_HPP

#define PALACE_ENGINE_LOG_LEVEL_FATAL 0
#define PALACE_ENGINE_LOG_LEVEL_ERROR 1
#define PALACE_ENGINE_LOG_LEVEL_WARNING 2
#define PALACE_ENGINE_LOG_LEVEL_INFO 3
#define PALACE_ENGINE_LOG_LEVEL_DEBUG 4
#define PALACE_ENGINE_LOG_LEVEL_TRACE 5

namespace palace {

enum class LogLevel {
    Fatal = PALACE_ENGINE_LOG_LEVEL_FATAL,
    Error = PALACE_ENGINE_LOG_LEVEL_ERROR,
    Warning = PALACE_ENGINE_LOG_LEVEL_WARNING,
    Info = PALACE_ENGINE_LOG_LEVEL_INFO,
    Debug = PALACE_ENGINE_LOG_LEVEL_DEBUG,
    Trace = PALACE_ENGINE_LOG_LEVEL_TRACE
};

};

#endif /* ATG_PALACE_ENGINE_LOG_LEVEL_HPP */
