#ifndef ATG_PALACE_ENGINE_PLATFORM_DETECTION_HPP
#define ATG_PALACE_ENGINE_PLATFORM_DETECTION_HPP

#define REBAR_PLATFORM_WINDOWS 0
#if defined(_WIN32) || defined(_WIN64)
#undef REBAR_PLATFORM_WINDOWS
#define REBAR_PLATFORM_WINDOWS 1

#if defined(_CONSOLE)
#define REBAR_PLATFORM_WINDOWS_CONSOLE_MODE 1
#else
#define REBAR_PLATFORM_WINDOWS_CONSOLE_MODE 0
#endif
#endif

#endif /* ATG_PALACE_ENGINE_PLATFORM_DETECTION_HPP */
